name: build
on: [push, pull_request]

jobs:
  linux-os:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Checkout
      uses: actions/checkout@v3
    - name: Prepare venv
      run: python -m venv venv
    - name: Install venv Dependencies
      run: venv/bin/python -m pip install --upgrade pip build
    - name: Build Package
      run: venv/bin/python -m build
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: honkypy-dist
        path: dist/
